title: DINish
email: dinish-site@playbeing.org
description: >-
  a fresh take on a classic typeface
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fonts.playbeing.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  playbeing
counter_dev_username: bertd2
#counter_dev_utcoffset: 2
plausible_url_base: https://plausible.playbeing.com
plausible_domain: fonts.playbeing.com

# Build settings
markdown: CommonMarkGhPages
theme: jekyll-theme-slate
plugins:
  #- jekyll-feed

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
