title: DINish
email: dinish-site@playbeing.org
description: >-
  a fresh take on a classic typeface
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fonts.playbeing.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  playbeing
google_analytics: UA-197060314-1

# Build settings
markdown: CommonMarkGhPages
theme: jekyll-theme-slate
plugins:
  #- jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
